default:
  timeout: 1
  threads: 50
  port_range: [1, 1024]
  enable_vuln_scan: false

quick:
  port_range: [1, 1000]
  timeout: 0.5

full:
  port_range: [1, 65535]
  timeout: 2
  enable_vuln_scan: true

stealth:
  threads: 10
  timeout: 3
  port_range: [20, 1024]
